- name: apt-get update
  apt:
    update_cache: yes
    cache_valid_time: 3600
  ignore_errors: True

- name: install java {{ java_installer_version }} and setup variables
  apt: name={{ item }} state=latest
  with_items:
      - "openjdk-{{ java_installer_version }}-jdk"

  
