- name: apt-get update
  apt:
    update_cache: yes
    cache_valid_time: 3600
  ignore_errors: True

- name: install java {{ java_installer_version }} and setup variables
  apt: name={{ item }} state=present
  with_items:
      - "openjdk-{{ java_installer_version }}-jdk"
  when: not install_zulu

- name: install zulu
  apt: deb=http://cdn.azul.com/zulu/bin/zulu{{ zulu_version }}-linux_amd64.deb
  when: install_zulu
